package com.zhimeng.caiwuweb.dao;

import com.zhimeng.caiwuweb.entity.Standard;
import org.springframework.stereotype.Repository;

@Repository
public interface StandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int insert(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int insertSelective(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    Standard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Standard record);
}